sudo: false
language: rust, dart

rust: stable
dart: stable

branches:
  only:
    - master

matrix:
  include:
    - os: windows
      before_script:
        - cd ./tool/clipboard/
      script: |
        cargo test
        cargo build
        pwsh ./copy_libs.ps1
        cd ../..
        dart pub get
        dart test

    - os:
      - linux
      - osx
      before_script:
        - cd ./tool/clipboard/
      script: |
        cargo test
        cargo build
        bash ./copy_libs.sh
        cd ../..
        dart pub get
        dart test
