lang: rust, dart

branches:
  only:
    - master

rust: stable
dart: stable

matrix:
  include:
    - os: windows
      before_script:
        - cd ./tool/clipboard/
      script: |
        cargo test
        cargo build
        copy .¥target¥debug¥clipboard.dll ..¥..¥
        cd ../..
        dart pub get
        dart test

    - os: linux
      before_script:
        - sudo apt-get install xorg-dev
        - cd ./tool/clipboard/
      script: |
        cargo test
        cargo build
        cp ./target/debug/libclipboard.so ../../
        cd ../..
        dart pub get
        dart test

    - os: osx
      before_script:
        - cd ./tool/clipboard/
      script: |
        cargo test
        cargo build
        cp ./target/debug/libclipboard.dylib ../../
        cd ../..
        dart pub get
        dart test
