branches:
  only:
    - master

matrix:
  include:
    - language: dart
      dart:
        - stable
      os:
        - windows
        - osx
        - linux
      script: 
        - dart pub get
        - dart test
        - dart analyze

    - language: rust
      rust: 
        - stable
      os:
        - windows
        - osx
        - linux
      before_script:
        - cd ./tool/clipboard/
      script:
        - cargo test
        - cargo check
