name: dart_clipboard
description: A package that operates the clipboard using the dynamic library in Rust.
version: 0.1.0
homepage: https://github.com/ippee/dart_clipboard

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  ffi: ^1.1.2
  test: ^1.17.10
